log:
  level: info

runner:
  timeout: 3h
  insecure: false
  fetch_interval: 2s
  fetch_timeout: 5s

container:
  network: ""
  privileged: false
  options: ""
  workdir_parent: ""
  docker_host: ""
  force_pull: false
  force_remove: true
  valid_volumes: []

host:
  workdir_parent: ""

cache:
  enabled: true
  dir: ""
  host: ""
  port: 0
  external_server: ""
